### ISSUE TITLE
Image from X not fetched succesfully

### ISSUE THREAD

**Issue by UmairJibran** [TechForPalestine/profile-pic-maker#12]
https://github.com/TechForPalestine/palestine-pfp-maker/assets/43789374/2ebc278a-2f4f-410a-943b-f32850843e9e

Steps to Re-Produce:
- Click "Use X Profile Pic"
- Enter Your X's Username

Expected Output
- Palestinian Flag's colour around my image

Current Output
- Nada (Entirety of the flag)

**Comment by tengkuhafidz** [comment]
That's weird. Just tested and it works on my end. 

Did you manage to try locally if this still consistently happens for you? and your fix in #13 will consistently resolve it? 🤔

**Comment by UmairJibran** [comment]
Yes @tengkuhafidz it was producing the same result locally for me as well, the fix resolved it for me locally.

Please go through it to see if that doesn't break anything else

**Comment by tengkuhafidz** [comment]
Did you manage to test locally if your fix in #13 will indeed fix the issue for you?

**Comment by UmairJibran** [comment]
yes, the fixed proposed in #13 resolved the issue for me locally

**Comment by tengkuhafidz** [comment]
let's try then.

**Comment by tengkuhafidz** [comment]
merged. please help to verify?

**Comment by UmairJibran** [comment]
https://github.com/TechForPalestine/palestine-pfp-maker/assets/43789374/0d4d2aa6-aacd-41af-803d-c30397cd879b

yep, works!

Thanks

**Comment by tengkuhafidz** [comment]
Beautiful. Thank you! 🚀
