### ISSUE TITLE
Inner Borderline too Thin

### ISSUE THREAD

**Issue by Peregrine-Falcon11** [TechForPalestine/profile-pic-maker#17]
Hi!
I think that the inner white borderline is too thin. When uploading a pfp to WhatsApp, the white borderline shows up broken up (like it's not a smooth circle but rather broken up), and my guess is that it's because when the image is scaled down quite a bit, the borderline is simply too thin. My suggestion is to either remove the white borderline altogether (I also think it would look better), or to make it thicker.

Thanks!

**Comment by tengkuhafidz** [comment]
This should be resolved now
