### ISSUE TITLE
Proper Code Formatting & Linting

### ISSUE THREAD

**Issue by UmairJibran** [TechForPalestine/profile-pic-maker#21]
Since we all have different preferences when it comes to styling, I think we should all follow a predefined style guide, we can use [Prettier](https://prettier.io/) and [EsLint](https://eslint.org/) to enforce styling and code structure.

We can add a github action that validates the code after a PR is opened

**Comment by thamudi** [comment]
I can take this issue. I have experience with linting and formatting nextjs and react projects
