### ISSUE TITLE
خطأ راجع وحدة تصفح المستخدم 

### ISSUE THREAD

**Issue by awmm4** [TechForPalestine/profile-pic-maker#38]

**Comment by Saleh23s** [comment]
?!!!!!

**Comment by UmairJibran** [comment]
@awmm4 can you please provide english translation? not everyone here who wants to help can speak arabic.

@awmm4 هل يمكنك توفير الترجمة الإنجليزية؟ ليس كل من يريد المساعدة هنا يمكنه التحدث باللغة العربية. (transalted with google)

**Comment by thamudi** [comment]
@awmm4  Can you please provide more information on the nature of the issue?
@awmm4 هل يمكنك تقديم المزيد من المعلومات حول طبيعة المشكلة؟  (translated with google)
