### ISSUE TITLE
profile picture maker

### ISSUE THREAD

**Issue by helayoty** [TechForPalestine/profile-pic-maker#6]
A simple browser-only web app that helps users to add a Palestine flag border around their profile picture - to show support for the cause. The app allows users to use their profile picture to make their stance visible.

Web app: https://palestineprofile.jariyah.app/
Repo: https://github.com/tengkuhafidz/palestine-pfp-maker

**Comment by helayoty** [comment]
via @pbiggar 

- is it ready to be launched? if not, nbd, just let me know
- please provide the right links to contribute and use it
- Any missing pieces we need to know?

**Comment by janajri** [comment]
This is now available publicly via https://ppm.techforpalestine.org/, closing.
